### ISSUE TITLE
Latest Version (1.1.1) not published on Maven

### ISSUE THREAD

**Issue by JamesPaden** [DocRaptor/docraptor-java#12]
https://search.maven.org/search?q=g:com.docraptor%20AND%20a:docraptor We seem to have Version 1.1.0 only, and our installation instructions use Maven by default - so I think all installations are broken?

**Comment by davidronk** [comment]
Latest version ([v2.0.0](https://github.com/DocRaptor/docraptor-java/releases/tag/v2.0.0)) is now live on [sonatype](https://search.maven.org/search?q=g:com.docraptor%20AND%20a:docraptor).
