### ISSUE TITLE
Appear to be missing a depencency

### ISSUE THREAD

**Issue by janxious** [DocRaptor/docraptor-java#8]
`"com.sun.jersey" % "jersey-core" % "1.7"` was required to get a scala project working using the maven-hosted jar. I think it is [this bug](https://github.com/swagger-api/swagger-codegen/issues/162) in swagger.

**Comment by davidronk** [comment]
This issue is resolved in the latest version ([v2.0.0](https://github.com/DocRaptor/docraptor-java/releases/tag/v2.0.0))
